// Package simulation runs dev-only synthetic mailbox traffic at a configurable rate.
//
// Pattern: Go goroutine + time.Ticker — lightweight concurrent timer without blocking HTTP handlers.
// Each tick generates one synthetic email and calls the same backend path as real webhooks.
package simulation

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/oferelboher/suspicious-email-triage/ingest-gateway/internal/backend"
	gwlogger "github.com/oferelboher/suspicious-email-triage/ingest-gateway/internal/logger"
	"github.com/oferelboher/suspicious-email-triage/ingest-gateway/internal/stats"
)

// Controller owns the background goroutine that emits synthetic emails.
type Controller struct {
	mu       sync.Mutex     // protects running, rate, seq, cancel
	running  bool           // true while loop goroutine is active
	rate     int            // current emails per minute (after cap)
	maxRate  int            // upper bound from MAILBOX_INGEST_MAX_EVENTS_PER_MIN
	seq      int64          // monotonic counter for unique simulated sender addresses
	cancel   context.CancelFunc // stops the loop goroutine via context cancellation
	stats    *stats.Store
	backend  *backend.Client
	onResult func(success bool, backendFailure bool) // optional Prometheus bridge from main
}

// NewController constructs a simulation controller tied to stats and the Node client.
func NewController(maxRate int, store *stats.Store, client *backend.Client, onResult func(bool, bool)) *Controller {
	return &Controller{
		maxRate: maxRate,
		stats:   store,
		backend: client,
		onResult: onResult,
	}
}

// Start enables simulation at emailsPerMinute (capped by maxRate).
func (c *Controller) Start(emailsPerMinute int) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.running {
		return fmt.Errorf("simulation already running")
	}
	rate := emailsPerMinute
	if rate < 1 {
		rate = 1
	}
	if rate > c.maxRate {
		rate = c.maxRate // clamp to env cap — UI cannot exceed MAILBOX_INGEST_MAX_EVENTS_PER_MIN
	}
	// context.WithCancel: Stop() calls cancel() to exit loop without killing the process.
	ctx, cancel := context.WithCancel(context.Background())
	c.running = true
	c.rate = rate
	c.cancel = cancel
	c.stats.SetSimulationState(true, rate)
	go c.loop(ctx, rate) // fire-and-forget goroutine — HTTP handler returns immediately
	return nil
}

// Stop cancels the simulation goroutine.
func (c *Controller) Stop() {
	c.mu.Lock()
	defer c.mu.Unlock()
	if !c.running {
		return
	}
	c.running = false
	if c.cancel != nil {
		c.cancel()
	}
	c.stats.SetSimulationState(false, 0)
}

// Status returns whether simulation is active and the configured rate.
func (c *Controller) Status() (enabled bool, rate int) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.running, c.rate
}

// loop ticks at the requested interval until context cancellation.
func (c *Controller) loop(ctx context.Context, rate int) {
	// interval = 60s / rate — e.g. 10/min → one email every 6 seconds.
	interval := time.Minute / time.Duration(rate)
	if interval < time.Millisecond {
		interval = time.Millisecond // safety floor for absurdly high rates in dev
	}
	ticker := time.NewTicker(interval)
	minuteReset := time.NewTicker(time.Minute) // resets lastMinuteReceived for dashboard
	defer ticker.Stop()
	defer minuteReset.Stop()

	// select multiplexes three channels — Go idiom for concurrent event loops.
	for {
		select {
		case <-ctx.Done():
			return // Stop() was called
		case <-minuteReset.C:
			c.stats.ResetMinuteCounter()
		case <-ticker.C:
			c.emitOne(ctx)
		}
	}
}

// emitOne creates a single synthetic review via the Node internal API.
func (c *Controller) emitOne(ctx context.Context) {
	c.mu.Lock()
	c.seq++
	n := c.seq
	c.mu.Unlock() // release lock before network I/O — do not hold mutex during HTTP call

	payload := backend.EmailPayload{
		SenderName:  "Mailbox Simulator",
		SenderEmail: fmt.Sprintf("mailbox-sim+%d@dev.local", n),
		Subject:     fmt.Sprintf("Simulated mailbox ingest #%d", n),
		Body:        fmt.Sprintf("Synthetic body generated by Go ingest-gateway at %s", time.Now().UTC().Format(time.RFC3339)),
		Source:      "mailbox_simulation",
	}
	_, err := c.backend.CreateMailboxReview(ctx, payload)
	if err != nil {
		c.stats.RecordError(true)
		gwlogger.Warn("simulation", "synthetic mailbox emit failed", map[string]interface{}{
			"seq": n, "error": err.Error(),
		})
		if c.onResult != nil {
			c.onResult(false, true)
		}
		return
	}
	c.stats.RecordSuccess("simulation", true)
	if c.onResult != nil {
		c.onResult(true, false)
	}
}
