// Package simulation runs dev-only synthetic mailbox traffic at a configurable rate.
//
// Pattern: Go goroutine + time.Ticker — lightweight concurrent timer without blocking HTTP handlers.
// Each tick generates one synthetic email and calls the same backend path as real webhooks.
package simulation

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/oferelboher/suspicious-email-triage/ingest-gateway/internal/backend"
	"github.com/oferelboher/suspicious-email-triage/ingest-gateway/internal/stats"
)

// Controller owns the background goroutine that emits synthetic emails.
type Controller struct {
	mu       sync.Mutex
	running  bool
	rate     int
	maxRate  int
	seq      int64
	cancel   context.CancelFunc
	stats    *stats.Store
	backend  *backend.Client
	onResult func(success bool, backendFailure bool)
}

// NewController constructs a simulation controller tied to stats and the Node client.
func NewController(maxRate int, store *stats.Store, client *backend.Client, onResult func(bool, bool)) *Controller {
	return &Controller{
		maxRate: maxRate,
		stats:   store,
		backend: client,
		onResult: onResult,
	}
}

// Start enables simulation at emailsPerMinute (capped by maxRate).
func (c *Controller) Start(emailsPerMinute int) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.running {
		return fmt.Errorf("simulation already running")
	}
	rate := emailsPerMinute
	if rate < 1 {
		rate = 1
	}
	if rate > c.maxRate {
		rate = c.maxRate
	}
	ctx, cancel := context.WithCancel(context.Background())
	c.running = true
	c.rate = rate
	c.cancel = cancel
	c.stats.SetSimulationState(true, rate)
	go c.loop(ctx, rate)
	return nil
}

// Stop cancels the simulation goroutine.
func (c *Controller) Stop() {
	c.mu.Lock()
	defer c.mu.Unlock()
	if !c.running {
		return
	}
	c.running = false
	if c.cancel != nil {
		c.cancel()
	}
	c.stats.SetSimulationState(false, 0)
}

// Status returns whether simulation is active and the configured rate.
func (c *Controller) Status() (enabled bool, rate int) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.running, c.rate
}

// loop ticks at the requested interval until context cancellation.
func (c *Controller) loop(ctx context.Context, rate int) {
	interval := time.Minute / time.Duration(rate)
	if interval < time.Millisecond {
		interval = time.Millisecond
	}
	ticker := time.NewTicker(interval)
	minuteReset := time.NewTicker(time.Minute)
	defer ticker.Stop()
	defer minuteReset.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-minuteReset.C:
			c.stats.ResetMinuteCounter()
		case <-ticker.C:
			c.emitOne(ctx)
		}
	}
}

// emitOne creates a single synthetic review via the Node internal API.
func (c *Controller) emitOne(ctx context.Context) {
	c.mu.Lock()
	c.seq++
	n := c.seq
	c.mu.Unlock()

	payload := backend.EmailPayload{
		SenderName:  "Mailbox Simulator",
		SenderEmail: fmt.Sprintf("mailbox-sim+%d@dev.local", n),
		Subject:     fmt.Sprintf("Simulated mailbox ingest #%d", n),
		Body:        fmt.Sprintf("Synthetic body generated by Go ingest-gateway at %s", time.Now().UTC().Format(time.RFC3339)),
		Source:      "mailbox_simulation",
	}
	_, err := c.backend.CreateMailboxReview(ctx, payload)
	if err != nil {
		c.stats.RecordError(true)
		if c.onResult != nil {
			c.onResult(false, true)
		}
		return
	}
	c.stats.RecordSuccess("simulation", true)
	if c.onResult != nil {
		c.onResult(true, false)
	}
}
