#!/usr/bin/env bash
# Replace old doc filenames with new prefixed names across the repository.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

replace() {
  local old="$1" new="$2"
  rg -l "$old" --glob '*.md' --glob '*.sh' --glob '*.py' --glob '*.yml' --glob '*.js' --glob 'integration_tests/*' 2>/dev/null | while read -r f; do
    sed -i "s|$old|$new|g" "$f"
  done
}

replace "arch_guide_overview.md" "arch_guide_overview.md"
replace "arch_assignment_historical.md" "arch_assignment_historical.md"
replace "arch_guide_system_comprehensive.md" "arch_guide_system_comprehensive.md"
replace "arch_guide_worker_pipeline.md" "arch_guide_worker_pipeline.md"
replace "roadmap_implemented_beyond_requirements.md" "roadmap_roadmap_implemented_beyond_requirements.md"
replace "roadmap_tbd.md" "roadmap_tbd.md"
replace "biz_guide_user.md" "biz_guide_user.md"
replace "auth_guide_rbac.md" "auth_guide_rbac.md"
replace "auth_guide_dev_admin_credentials.md" "auth_guide_dev_admin_credentials.md"
replace "auth_guide_dev_auth_recovery.md" "auth_guide_dev_auth_recovery.md"
replace "auth_guide_dev_password_reset.md" "auth_guide_dev_password_reset.md"
replace "auth_guide_dev_smtp_recovery.md" "auth_guide_dev_smtp_recovery.md"
replace "auth_guide_google_oauth.md" "auth_guide_google_oauth.md"
replace "auth_guide_django_admin_users.md" "auth_guide_django_admin_users.md"
replace "api_reference_rest.md" "api_reference_rest.md"
replace "graph_guide_neo4j_phishing.md" "graph_guide_neo4j_phishing.md"
replace "graph_demo_neo4j_phishing.md" "graph_demo_neo4j_phishing.md"
replace "ui_guide_analytics_charts.md" "ui_guide_analytics_charts.md"
replace "search_guide_elasticsearch_reviews.md" "search_guide_elasticsearch_reviews.md"
replace "ui_guide_color_themes.md" "ui_guide_color_themes.md"
replace "stack_guide_windows_startup.md" "stack_guide_windows_startup.md"
replace "stack_guide_windows_docker_databases.md" "stack_guide_windows_docker_databases.md"
replace "stack_guide_frontend_api.md" "stack_guide_frontend_api.md"
replace "stack_guide_full_stack.md" "stack_guide_full_stack.md"
replace "stack_guide_versions_builds.md" "stack_guide_versions_builds.md"
replace "stack_guide_deployment.md" "stack_guide_stack_guide_deployment.md"
replace "stack_guide_production.md" "stack_guide_production.md"
replace "stack_guide_dev_database_credentials.md" "stack_guide_dev_database_credentials.md"
replace "stack_guide_pre_push_verification.md" "stack_guide_pre_push_verification.md"
replace "stack_guide_running_tests.md" "stack_guide_running_tests.md"
replace "ops_guide_health_uptime.md" "ops_guide_health_uptime.md"
replace "ops_guide_central_logging.md" "ops_guide_central_logging.md"
replace "ops_guide_metrics_alerting.md" "ops_guide_metrics_alerting.md"
replace "ops_guide_kubernetes_helm.md" "ops_guide_kubernetes_helm.md"
replace "ci_guide_environment_builds.md" "ci_guide_environment_builds.md"
replace "ci_guide_pipeline_architecture.md" "ci_guide_pipeline_arch_guide_overview.md"
replace "ci_guide_node_python_django_legacy.md" "ci_guide_node_python_django_legacy.md"
replace "data_guide_kafka_events.md" "data_guide_kafka_events.md"
replace "data_guide_prefect_dbt_demo.md" "data_guide_prefect_dbt_demo.md"
replace "data_guide_mock_llm.md" "data_guide_mock_llm.md"
replace "tech_neo4j_setup_wsl_windows.md" "tech_neo4j_setup_wsl_windows.md"
replace "tech_postgresql_dbeaver_windows.md" "tech_postgresql_dbeaver_windows.md"
replace "tech_postgresql_dbeaver_auth_logs.md" "tech_postgresql_dbeaver_auth_logs.md"
replace "tech_mongodb_compass_windows.md" "tech_mongodb_compass_windows.md"
replace "tech_redis_insight_windows.md" "tech_redis_insight_windows.md"
replace "tech_env_configuration.md" "tech_env_configuration.md"
replace "tech_cursor_project_rules.md" "tech_tech_cursor_project_rules.md"

echo "Link replacements done."
